// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructuralDesignStudio.DataAccessLayer.Concrete.Context;

#nullable disable

namespace StructuralDesignStudio.DataAccessLayer.Migrations
{
    [DbContext(typeof(StructuralContext))]
    partial class StructuralContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StructuralDesignStudio.EntityLayer.Concrete.StructuralElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("FloorLevel")
                        .HasColumnType("int");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialID");

                    b.ToTable("StructuralElement");

                    b.HasDiscriminator<string>("ElementType").HasValue("StructuralElement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StructuralDesignStudio.EntityLayer.Concrete.StructuralMaterial", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<double>("CompressiveStrength")
                        .HasColumnType("float");

                    b.Property<double>("Density")
                        .HasColumnType("float");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterialType")
                        .HasColumnType("int");

                    b.HasKey("MaterialId");

                    b.ToTable("StructuralMaterials");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            CompressiveStrength = 25.0,
                            Density = 2.3999999999999999,
                            MaterialName = "C25 Concrete",
                            MaterialType = 0
                        },
                        new
                        {
                            MaterialId = 2,
                            CompressiveStrength = 30.0,
                            Density = 2.5,
                            MaterialName = "C30 Concrete",
                            MaterialType = 0
                        },
                        new
                        {
                            MaterialId = 3,
                            CompressiveStrength = 35.0,
                            Density = 2.5,
                            MaterialName = "C35 Concrete",
                            MaterialType = 0
                        },
                        new
                        {
                            MaterialId = 4,
                            CompressiveStrength = 40.0,
                            Density = 2.6000000000000001,
                            MaterialName = "C40 Concrete",
                            MaterialType = 0
                        },
                        new
                        {
                            MaterialId = 5,
                            CompressiveStrength = 45.0,
                            Density = 2.6000000000000001,
                            MaterialName = "C45 Concrete",
                            MaterialType = 0
                        },
                        new
                        {
                            MaterialId = 6,
                            CompressiveStrength = 355.0,
                            Density = 7.8499999999999996,
                            MaterialName = "S355 Steel",
                            MaterialType = 1
                        },
                        new
                        {
                            MaterialId = 7,
                            CompressiveStrength = 420.0,
                            Density = 7.8499999999999996,
                            MaterialName = "S420 Steel",
                            MaterialType = 1
                        },
                        new
                        {
                            MaterialId = 8,
                            CompressiveStrength = 500.0,
                            Density = 7.8499999999999996,
                            MaterialName = "S500 Steel",
                            MaterialType = 1
                        },
                        new
                        {
                            MaterialId = 9,
                            CompressiveStrength = 20.0,
                            Density = 1.8,
                            MaterialName = "Lightweight Concrete",
                            MaterialType = 0
                        },
                        new
                        {
                            MaterialId = 10,
                            CompressiveStrength = 60.0,
                            Density = 2.7000000000000002,
                            MaterialName = "High Strength Concrete",
                            MaterialType = 0
                        });
                });

            modelBuilder.Entity("StructuralDesignStudio.EntityLayer.Concrete.StructuralBeam", b =>
                {
                    b.HasBaseType("StructuralDesignStudio.EntityLayer.Concrete.StructuralElement");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.ToTable("StructuralElement", t =>
                        {
                            t.Property("Height")
                                .HasColumnName("StructuralBeam_Height");

                            t.Property("Width")
                                .HasColumnName("StructuralBeam_Width");
                        });

                    b.HasDiscriminator().HasValue("Beam");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 1,
                            MaterialID = 2,
                            Name = "B1",
                            Height = 50.0,
                            Length = 600.0,
                            Width = 30.0
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 1,
                            MaterialID = 3,
                            Name = "B2",
                            Height = 60.0,
                            Length = 650.0,
                            Width = 30.0
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 2,
                            MaterialID = 4,
                            Name = "B3",
                            Height = 60.0,
                            Length = 700.0,
                            Width = 35.0
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 2,
                            MaterialID = 5,
                            Name = "B4",
                            Height = 70.0,
                            Length = 750.0,
                            Width = 40.0
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 3,
                            MaterialID = 2,
                            Name = "B5",
                            Height = 65.0,
                            Length = 800.0,
                            Width = 35.0
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 3,
                            MaterialID = 3,
                            Name = "B6",
                            Height = 70.0,
                            Length = 850.0,
                            Width = 40.0
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 4,
                            MaterialID = 4,
                            Name = "B7",
                            Height = 75.0,
                            Length = 900.0,
                            Width = 45.0
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 4,
                            MaterialID = 5,
                            Name = "B8",
                            Height = 80.0,
                            Length = 950.0,
                            Width = 45.0
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 5,
                            MaterialID = 10,
                            Name = "B9",
                            Height = 80.0,
                            Length = 1000.0,
                            Width = 50.0
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 5,
                            MaterialID = 10,
                            Name = "B10",
                            Height = 85.0,
                            Length = 1050.0,
                            Width = 50.0
                        });
                });

            modelBuilder.Entity("StructuralDesignStudio.EntityLayer.Concrete.StructuralColumn", b =>
                {
                    b.HasBaseType("StructuralDesignStudio.EntityLayer.Concrete.StructuralElement");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Column");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 1,
                            MaterialID = 2,
                            Name = "C1",
                            Depth = 40.0,
                            Height = 300.0,
                            Width = 40.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 1,
                            MaterialID = 3,
                            Name = "C2",
                            Depth = 45.0,
                            Height = 300.0,
                            Width = 45.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 2,
                            MaterialID = 4,
                            Name = "C3",
                            Depth = 50.0,
                            Height = 300.0,
                            Width = 50.0
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 2,
                            MaterialID = 5,
                            Name = "C4",
                            Depth = 60.0,
                            Height = 300.0,
                            Width = 60.0
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 3,
                            MaterialID = 2,
                            Name = "C5",
                            Depth = 50.0,
                            Height = 320.0,
                            Width = 40.0
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 3,
                            MaterialID = 3,
                            Name = "C6",
                            Depth = 55.0,
                            Height = 320.0,
                            Width = 45.0
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 4,
                            MaterialID = 4,
                            Name = "C7",
                            Depth = 60.0,
                            Height = 320.0,
                            Width = 50.0
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 4,
                            MaterialID = 5,
                            Name = "C8",
                            Depth = 65.0,
                            Height = 320.0,
                            Width = 55.0
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 5,
                            MaterialID = 10,
                            Name = "C9",
                            Depth = 60.0,
                            Height = 350.0,
                            Width = 60.0
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 5,
                            MaterialID = 10,
                            Name = "C10",
                            Depth = 65.0,
                            Height = 350.0,
                            Width = 65.0
                        });
                });

            modelBuilder.Entity("StructuralDesignStudio.EntityLayer.Concrete.StructuralSlab", b =>
                {
                    b.HasBaseType("StructuralDesignStudio.EntityLayer.Concrete.StructuralElement");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<double>("Thickness")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.ToTable("StructuralElement", t =>
                        {
                            t.Property("Length")
                                .HasColumnName("StructuralSlab_Length");

                            t.Property("Width")
                                .HasColumnName("StructuralSlab_Width");
                        });

                    b.HasDiscriminator().HasValue("Slab");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 1,
                            MaterialID = 2,
                            Name = "S1",
                            Length = 1000.0,
                            Thickness = 15.0,
                            Width = 800.0
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 1,
                            MaterialID = 3,
                            Name = "S2",
                            Length = 1200.0,
                            Thickness = 15.0,
                            Width = 900.0
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 2,
                            MaterialID = 4,
                            Name = "S3",
                            Length = 1300.0,
                            Thickness = 18.0,
                            Width = 950.0
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 2,
                            MaterialID = 5,
                            Name = "S4",
                            Length = 1400.0,
                            Thickness = 18.0,
                            Width = 1000.0
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 3,
                            MaterialID = 2,
                            Name = "S5",
                            Length = 1500.0,
                            Thickness = 20.0,
                            Width = 1100.0
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 3,
                            MaterialID = 3,
                            Name = "S6",
                            Length = 1600.0,
                            Thickness = 20.0,
                            Width = 1200.0
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 4,
                            MaterialID = 4,
                            Name = "S7",
                            Length = 1700.0,
                            Thickness = 22.0,
                            Width = 1300.0
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 4,
                            MaterialID = 5,
                            Name = "S8",
                            Length = 1800.0,
                            Thickness = 22.0,
                            Width = 1400.0
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 5,
                            MaterialID = 10,
                            Name = "S9",
                            Length = 1900.0,
                            Thickness = 25.0,
                            Width = 1500.0
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorLevel = 5,
                            MaterialID = 10,
                            Name = "S10",
                            Length = 2000.0,
                            Thickness = 25.0,
                            Width = 1600.0
                        });
                });

            modelBuilder.Entity("StructuralDesignStudio.EntityLayer.Concrete.StructuralElement", b =>
                {
                    b.HasOne("StructuralDesignStudio.EntityLayer.Concrete.StructuralMaterial", "Material")
                        .WithMany("StructuralElements")
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("StructuralDesignStudio.EntityLayer.Concrete.StructuralMaterial", b =>
                {
                    b.Navigation("StructuralElements");
                });
#pragma warning restore 612, 618
        }
    }
}
